# Defaults for training config.
lr: 1.0e-4
batch_size: 8
schedule_sampler: loss-second-moment
data_dir: data/augmented_cell
weight_decay: 0.0
lr_anneal_steps: 0
microbatch: -1  # -1 disables microbatches
ema_rate: 0.9999  # comma-separated list of EMA values
log_interval: 50
save_interval: 2000
resume_checkpoint: ""
use_fp16: False
fp16_scale_growth: 1.0e-3